export const person = {
  name: "Mariusz Matusiewicz",
  email: "mariusz.myprojects@gmail.com",
  description:
    "I'm passionate about frontend development, especially using React. My goal is to develop my skills and turn this passion into additional work.",
  invitation:
    "I'm always open to new projects whenever I have time. If you're planning a website, dashboard, and need help bringing your ideas to life, feel free to contact me.",
  github: {
    name: "mariuszmmm",
    link: "https://github.com/mariuszmmm",
    exclusions: [
      { name: "Mariuszmmm" },
      { name: "Calculator" },
      { name: "Photo-catalog-backend" },
    ],
  },
  facebook: null,
  linkedin: {
    link: "https://www.linkedin.com/in/mariuszmatusiewicz",
  },
  instagram: null,
  skills: [
    "Semantic and accessible HTML",
    "Responsive Web Design",
    "Teamwork",
    "Markdown",
    "Immutability",
    "CSS BEM convention",
    "CSS Flexbox",
    "CSS Grid",
    "React Router",
    "Redux-Saga",
    "Redux (Toolkit)",
    "React Hooks",
    "Error handling",
    "Working with API (fetch, axios)",
    "JavaScript ES6+",
    "Promises, Async/Await",
    "GitHub Pull Requests & Review",
    "Trello",
    "Scrum",
    "NPM",
    "React",
    "Styled Components",
    "Git",
  ],
  toLearn: [
    "React Context",
    "React Native",
    "LUA",
    "Cypress",
    "TypeScript",
    "Node.js",
    "Unit testing",
    "JS classes",
    "MongoDB",
  ],
};
